# get data

In [1]:
import pandas as pd
from src.api.service.inference import Inference


x_data = pd.read_csv('/Users/macbookpro/PycharmProjects/projet_credit_risk_modeling/data/processed/splited_data/x_test.csv')
y_data = pd.read_csv('/Users/macbookpro/PycharmProjects/projet_credit_risk_modeling/data/processed/splited_data/y_test.csv')

/Users/macbookpro/PycharmProjects/projet_credit_risk_modeling/.venv/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
(CVXPY) May 26 08:27:37 PM: Encountered unexpected exception importing solver GLOP:
RuntimeError('Unrecognized new version of ortools (9.15.6755). Expected < 9.15.0. Please open a feature request on cvxpy to enable support for this version.')
(CVXPY) May 26 08:27:37 PM: Encountered unexpected exception importing solver PDLP:
RuntimeError('Unrecognized new version of ortools (9.15.6755). Expected < 9.15.0. Please open a feature request on cvxpy to enable support for this version.')

In [ ]:
x_data.columns

Observation

In [2]:
ob1 = x_data.sample(1)


ob1

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
3468,25,175000,RENT,2.0,PERSONAL,A,25000,8.9,0.14,N,2

In [3]:
ob2 = x_data.sample(1)

ob2

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
3099,23,40000,RENT,7.0,EDUCATION,C,10000,10.995555,0.25,N,2

# inference

In [4]:
inference = Inference()

In [5]:
result = inference.predict(request_data=ob1,threshold=0.24999999999999992)

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]
Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]
Downloading artifacts: 100%|██████████| 1/1 [00:00<00:00, 23.95it/s]


Downloading artifacts: 100%|██████████| 1/1 [00:00<00:00, 32.50it/s]
Downloading artifacts: 100%|██████████| 1/1 [00:03<00:00,  3.47s/it]
Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]
Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts: 100%|██████████| 1/1 [00:00<00:00, 21.91it/s]


Downloading artifacts: 100%|██████████| 1/1 [00:00<00:00, 25.36it/s]

Downloading artifacts: 100%|██████████| 1/1 [00:02<00:00,  2.66s/it]
Downloading artifacts: 100%|██████████| 1/1 [00:02<00:00,  2.67s/it]

In [6]:
pd.DataFrame(result)

   prediction  probability  threshold
0           1     0.281474       0.25

In [7]:
inference = Inference()

In [8]:
result = inference.predict(request_data=ob2,threshold=0.24999999999999992)

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]
Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts: 100%|██████████| 1/1 [00:00<00:00, 24.53it/s]


Downloading artifacts: 100%|██████████| 1/1 [00:00<00:00, 26.25it/s]

Downloading artifacts: 100%|██████████| 1/1 [00:03<00:00,  3.41s/it]
Downloading artifacts: 100%|██████████| 1/1 [00:03<00:00,  3.41s/it]
Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]
Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]
Downloading artifacts: 100%|██████████| 1/1 [00:00<00:00, 31.14it/s]


Downloading artifacts: 100%|██████████| 1/1 [00:00<00:00, 33.26it/s]
Downloading artifacts: 100%|██████████| 1/1 [00:02<00:00,  2.74s/it]

In [9]:
pd.DataFrame(result)

   prediction  probability  threshold
0           1     0.382748       0.25